export const MAX_ALLOWED_PLAYERS = 8;

export const CORNER_CELL_CAPACITY = 1;
export const BORDER_CELL_CAPACITY = 2;
export const REGULAR_CELL_CAPACITY = 3;

//Player timeout in s milli seconds
export const PLAYER_TIMEOUT = 10000;

export const COLOR = [
  'red',
  'green',
  'blue',
  'pink',
  'orange',
  'yellow',
  'purple',
  'teal',
];

export const PLAYERNAMES = [
  'Obi-Wan Kenobi',
  'Han Solo',
  'Luke Skywalker',
  'Yoda',
  'Darth Vader',
  'R2-D2',
  'Darth Maul',
  'Chewbacca',
  'Princess Leia',
  'General Grievous',
  'C-3PO',
  'Emperor Palpatine',
  'Boba Fett',
  'Jabba',
  'Lando Calrissian',
  'Mace Windu',
  'Padmé Amidala',
  'Count Dooku',
  'Qui-Gon Jinn',
  'Asajj Ventress',
  'Plo Koon',
  'Ben Skywalker',
  'Kit Fisto',
  'Savage Opress',
  'Jaina Solo',
  'Jango Fett',
  'Revan',
  'Ahsoka Tano',
  'Admiral Ackbar',
  'Mara Jade',
  'Cad Bane',
  'Wedge Antilles',
  'Shaak Ti',
  'Bastila Shan',
  'Grand Moff Tarkin',
  'Anakin Solo',
  'Jacen Solo',
  'Captain Rex',
  'Darth Bane',
  'Darth Nihilus',
  'Aurra Sing',
  'Kyle Katarn',
  'Darth Krayt',
  'Galen Marek',
  'Quinlan Vos',
  'Luminara Unduli',
  'Commander Cody',
  'Admiral Thrawn',
  'Kylo Ren',
  'Rey',
  'BB-8',
  'Darth Malgus',
  'Admiral Piett',
  'Owen Lars',
  'Beru Lars',
  'Commander Gree',
  'Darth Plagueis',
  'Clone Commander Bly',
  'Lord Kaan',
  'Biggs Darklighter',
  'Kanan Jarrus',
  'Poe Dameron',
  'Ezra Bridger',
  'Sabine Wren',
  'Zeb Orrelios',
  'Greedo',
  'Chopper',
  'Hera Syndulla',
  'Bossk',
  'Aayla Secura',
  'Commander Fox',
  'Commander Thire',
  'Commander Appo',
  'Commander Bacara',
  'Commander ',
  'Nute Gunray',
  'Yaddle',
];
